### ISSUE TITLE
Feedback week-02 homework

### ISSUE THREAD

**Issue by zkwsk** [paredesrichard/hyf-html-css#4]
Very good work!

The page looks very close to the provided design, although I agree with Amrita that the font-size in the aside should be smaller.

Your HTML looks very clean. Good use of semantic markup, so it's nice to see that you've learned from the feedback last time.

One small thing. If you position the article div before the aside you will have the most important content first and that may help accessibility a bit.

I like the fact that you seem to have the more general styles on html elements and then as styles get more specific you use classes. That's an important principle in keeping your CSS maintainable.

You seem to have some experience already with HTML and CSS so if you want to try to challenge yourself a bit more I suggest that you have a loo into learning some good principles for maintaining CSS in larger systems. Have a look at BEM for example: https://css-tricks.com/bem-101/

**Comment by paredesrichard** [comment]
Thanks for your feedback Zaki! I have reorganized my html sections / semantics as per your suggestion.  I just hope that I understood what you mean by putting the article div before the aside section. If you still have time, please review the revised html code.  

I only knew some basic html tags like body, h1, td, th, tr, etc.  zero knowledge with CSS and other stuff, and learned about them only last Feb, during the evaluation period for HYF.  It's been a great learning experience thanks to you guys!  We appreciate all your efforts!
